// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/colegios" | "/colegios/[slug]" | "/no-disponible"
type AppRouteHandlerRoutes = "/api/contact"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/colegio-coyancura" | "/colegio-coyancura.html" | "/colegio-las-condes" | "/colegio-las-condes.html" | "/colegio-leonardo-da-vinci" | "/colegio-leonardo-da-vinci.html" | "/colegio-nuestra-senora-del-rosario" | "/colegio-nuestra-senora-del-rosario.html" | "/colegio-san-francisco" | "/colegio-san-francisco-del-alba" | "/colegio-san-francisco-del-alba.html" | "/colegio-san-francisco.html" | "/colegio-simon-bolivar" | "/colegio-simon-bolivar.html" | "/colegios" | "/colegios.html" | "/pages/no-disponible" | "/pages/no-disponible.html"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/contact": {}
  "/colegios": {}
  "/colegios/[slug]": { "slug": string; }
  "/no-disponible": {}
  "/colegio-coyancura": {}
  "/colegio-coyancura.html": {}
  "/colegio-las-condes": {}
  "/colegio-las-condes.html": {}
  "/colegio-leonardo-da-vinci": {}
  "/colegio-leonardo-da-vinci.html": {}
  "/colegio-nuestra-senora-del-rosario": {}
  "/colegio-nuestra-senora-del-rosario.html": {}
  "/colegio-san-francisco": {}
  "/colegio-san-francisco-del-alba": {}
  "/colegio-san-francisco-del-alba.html": {}
  "/colegio-san-francisco.html": {}
  "/colegio-simon-bolivar": {}
  "/colegio-simon-bolivar.html": {}
  "/colegios": {}
  "/colegios.html": {}
  "/pages/no-disponible": {}
  "/pages/no-disponible.html": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
