var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/colegios/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jjw6s1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1d1g2kj.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/_0u5at6q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1r461z9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hvdm_8._.js")
R.c("server/chunks/ssr/_1ymacwp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_colegios_[slug]_page_actions_0sakwxh.js")
R.m(16235)
module.exports=R.m(16235).exports
